version: '2.1'

services:
  stickerapp:
    image: stickerapp:latest
    build: .
    environment:
      NODE_ENV: development
      MONDGODB_URL: 
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server/index.js