'use strict';

const bodyParser = require('body-parser');
const express = require('express');
const request = require('request');

const CART_URL = `${process.env.SESSION_SERVICE_URL}/cart`;
const router = express.Router();

router.get('/', function stickerRouteCart(req, res) {
    res.render('index', { pageTitle: 'Cart', entry: 'cart' });
});

router.use(bodyParser.json());

router.use((req, res, next) => {
    var sessionId = req.query.token || req.body.token;
    if (!req.user) {
        // If the user is unauthenticated, use
        // the session uuid generated by the client as a
        // temporary 'user id'
        req.user = { id: sessionId };
        next();
    } else {
        // If the user is authenticated, pass the client's
        // session uuid so that any items that were added
        // to the cart prior to the user authenticating can
        // be merged into the user's cart.
        request.put(`${CART_URL}/transfer/${sessionId}`, {
            headers: { stickerUserId: req.user.id },
            json: true
        }, (error, response) => {
            if (error) {
                console.error(error);
            }
            next();
        });
    }
});

router.get('/api/items', function getCart(req, res) {

    request.get(CART_URL, {
        headers: { stickerUserId: req.user.id },
        json: true
    }, (error, response) => {
        if (error) {
            console.error(error);
            res.sendStatus(500);
        } else {
            res.send(response.body);
        }
    });
});

router.delete('/api/items/:item_id', function removeItem(req, res) {

    console.log('Item targeted', req.params.item_id);
    request.delete(`${CART_URL}/${req.params.item_id}`, {
        headers: { stickerUserId: req.user.id },
        json: true
    }, (error, response) => {
        if (error) {
            console.error(error);
            res.sendStatus(500);
        } else {
            res.send(response.body);
        }
    });
});

router.put('/api/items/:item_id', function addItem(req, res) {

    request.put(`${CART_URL}/${req.params.item_id}`, {
        headers: { stickerUserId: req.user.id },
        body: req.body,
        json: true
    }, (error, response) => {
        if (error) {
            console.error(error);
            res.sendStatus(500);
        } else {
            res.send(response.body);
        }
    });
});

module.exports = router;
