'use strict';

const bodyParser = require('body-parser');
const express = require('express');
const request = require('request');

const appInsights = require("applicationinsights");
const iKey = require('../config/appinsights-config').aiSettings.iKey;
const aiClient = appInsights.getClient(iKey);

const CART_URL = `${process.env.SESSION_SERVICE_URL}/cart`;
const router = express.Router();

router.get('/', function stickerRouteCart(req, res) {
    res.render('index', { pageTitle: 'Cart', entry: 'cart' });
});

router.use(bodyParser.json());

// TODO this enables carts for unauthenticated users, passing the uuid
// generated by the client to the session service as the user's id.
// Moving the user's unauthenticated cart to one stored with their
// permanent id upon login is unimplemented.
router.use((req, res, next) => {
    // the client passes the uuid in the query string for GET
    // requests, in body JSON for PUT
    if (!req.user) {
        req.user = { id: req.query.token || req.body.token };
    }

    next();
});

router.get('/api/items', function getCart(req, res) {

    aiClient.trackRequest(req, res);

    request.get(CART_URL, {
        headers: { stickerUserId: req.user.id },
        json: true
    }, (error, response) => {
        if (error) {
            console.error(error);
            res.sendStatus(500);
        } else {
            res.send(response.body);
        }
    });
});

router.delete('/api/items/:item_id', function removeItem(req, res) {

    aiClient.trackRequest(req, res);

    console.log('Item targeted', req.params.item_id);
    request.delete(`${CART_URL}/${req.params.item_id}`, {
        headers: { stickerUserId: req.user.id },
        json: true
    }, (error, response) => {
        if (error) {
            console.error(error);
            res.sendStatus(500);
        } else {
            res.send(response.body);
        }
    });
});

router.put('/api/items/:item_id', function addItem(req, res) {

    aiClient.trackRequest(req, res);

    request.put(`${CART_URL}/${req.params.item_id}`, {
        headers: { stickerUserId: req.user.id },
        body: req.body,
        json: true
    }, (error, response) => {
        if (error) {
            console.error(error);
            res.sendStatus(500);
        } else {
            res.send(response.body);
        }
    });
});

module.exports = router;
