apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "activeDirectory.secret.name" . }}"
  labels:
{{ include "stickerapp.common.labels" . | indent 4 }}
type: Opaque
data:
  client-secret: "{{ .Values.azureActiveDirectory.clientSecret | b64enc }}"