{{- if not .Values.local.redis -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "redis.host" . }}"
  labels:
{{ include "stickerapp.common.labels" . | indent 4 }}
type: Opaque
data:
  redis-password: "{{ .Values.redisPassword | b64enc }}"
{{- end -}}