{{- if .Values.dockercfg }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockercfg
metadata:
  name: "{{ template "registry.secret.name" . }}"
data:
  .dockercfg: {{ .Values.dockercfg | quote }}
{{- end }}
