dependencies:
  - name: kafka
    version: 0.1.2
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
  - name: mongodb
    version: 0.4.10
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: local.mongodb
  - name: mysql
    version: 0.2.6
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: local.mysql
  - name: redis
    version: 0.5.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: local.redis
